### ISSUE TITLE
rewrite in a sane language

### ISSUE THREAD

**Issue by tizu69** [Bluemethyst/Postmaster-Mobile#1]
![image](https://github.com/user-attachments/assets/e937327e-6423-4beb-8ffe-3e1826474a72)
![image](https://github.com/user-attachments/assets/f2858fa4-4b73-487d-a31a-6557ca0b5fcd)
![image](https://github.com/user-attachments/assets/b7c3850d-a3c4-4805-a2e9-8a26d5050a67)
![image](https://github.com/user-attachments/assets/79a3657f-0e68-477f-b7c7-f15e6a7671e9)
![image](https://github.com/user-attachments/assets/a01bd39c-d460-4766-badc-2b2b4b052847)
![image](https://github.com/user-attachments/assets/7244658b-a5ca-4d18-860e-675721194ab8)
![image](https://github.com/user-attachments/assets/3845d46d-11b2-45ac-9d4b-2258b2e6e6eb)
![image](https://github.com/user-attachments/assets/390069f5-1f59-4927-affb-5ef72cdb16e0)
![image](https://github.com/user-attachments/assets/3d6e5d87-947e-44a0-a4a9-6b8f458d77d8)
![image](https://github.com/user-attachments/assets/58ebe316-5097-4ffb-bb9d-2f2aa131389c)
![image](https://github.com/user-attachments/assets/d7fd7393-c5ea-4333-8e8c-410e32d5644c)
![image](https://github.com/user-attachments/assets/b316d4e3-60e7-4603-a116-3973d5d137c1)
![image](https://github.com/user-attachments/assets/4aada5e4-af66-464a-812a-7ce3a3434d7f)
![image](https://github.com/user-attachments/assets/facbd548-3375-41a4-bff1-c8978d05e4fa)
![image](https://github.com/user-attachments/assets/197026eb-fec3-489b-abfd-0588519f7c57)
![Uploading image.png…]()

**Comment by Bluemethyst** [comment]
lmao no

**Comment by tizu69** [comment]
gdfg
